name: Java CI with Gradle 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 12 * * 3'   # каждую среду в 12:30 UTC
    - cron: '0 22 * * 5'     # каждую пятницу в 22:00 UTC

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
        java: [11, 13, 17] 
    steps:
    - uses: actions/checkout@v4
    

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'  
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
    
    - name: Make gradlew executable
      run: chmod +x gradlew
    
    - name: Build with Gradle Wrapper
      run: ./gradlew build
